# 矩阵乘法演示代码

In [2]:
import numpy as np

## 标量乘法演示

In [3]:
# 定义2个标量
a = 2
b = 3
# 标量乘法
c = a * b
# 输出结果
print("标量乘法输出结果a * b =", c)

标量乘法输出结果a * b = 6


## 向量乘法演示

In [4]:
# 定义2个长度为4的向量
a = np.array([0, 1, 2, 3])
b = np.array([2, 4, 6, 8])
# 向量乘法
c = np.matmul(a, b)
# 输出结果
print("向量乘法输出结果a * b =", c)

向量乘法输出结果a * b = 40


### 具有负数元素的向量乘法演示

In [5]:
# 定义2个长度为4的向量
a = np.array([0, 1, -2, 3])
b = np.array([-2, 4, 6, 8])
# 向量乘法
c = np.matmul(a, b)
# 输出结果
print("向量乘法输出结果a * b =", c)

向量乘法输出结果a * b = 16


## 矩阵与向量乘法演示

In [6]:
# 定义1个长度为4的向量
a = np.array([0, 1, -2, 3])
# 定义1个大小为[4, 4]的矩阵
B = np.array([[2, -4, 6, 8],
              [1, 0, -2, 3],
              [3, -1, 0, 4],
              [5, -3, 4, 1]])
# 矩阵与向量乘法
c = np.matmul(B, a)
# 输出结果
print("矩阵与向量乘法输出结果B * a =", c)

矩阵与向量乘法输出结果B * a = [ 8 13 11 -8]


## 矩阵与矩阵乘法演示

In [7]:
# 定义1个大小为[4, 4]的矩阵
A = np.array([[0, 1, -2, 3],
              [1, 2, -2, 3],
              [3, 0, -2, 2],
              [4, -1, 0, 3]])

B = np.array([[2, -4, 6, 8],
              [1, 0, -2, 3],
              [3, -1, 0, 4],
              [5, -3, 4, 1]])
# 矩阵与向量乘法
C = np.matmul(A, B)
# 输出结果
print("矩阵乘法输出结果A * B =\n", C)

矩阵乘法输出结果A * B =
 [[ 10  -7  10  -2]
 [ 13 -11  14   9]
 [ 10 -16  26  18]
 [ 22 -25  38  32]]


## 传统光学交叉阵列向量与矩阵乘法演示

In [8]:
# 输入向量
a = np.array([1e-3, 0.8e-3, 0.5e-3, 0.2e-3])

# 矩阵数据
B = np.array([[0.5, 0.2, 0.8, 0.4],
              [0.5, 0.4, 0.2, 0.8],
              [0.8, 0.6, 0.1, 0.5],
              [0.1, 0.1, 0.8, 0.5]])

# 衰减值转化为dB
B_dB = 10 * np.log10(B / 1)
print("矩阵衰减值转化为dB = \n", B_dB)

# 矩阵乘法
c = np.matmul(a, B)

# 输出结果
print("向量乘法输出结果a * b =", c)

# 考虑交叉阵列结构平均分配功率
c_out = c / 16
print("实际输出光功率值c = ", c_out)

# 转化为dBm
c_dBm = 10 * np.log10(c_out / 1e-3)
print("转化为dBm的值 = ", c_dBm)

矩阵衰减值转化为dB = 
 [[ -3.01029996  -6.98970004  -0.96910013  -3.97940009]
 [ -3.01029996  -3.97940009  -6.98970004  -0.96910013]
 [ -0.96910013  -2.2184875  -10.          -3.01029996]
 [-10.         -10.          -0.96910013  -3.01029996]]
向量乘法输出结果a * b = [0.00132 0.00084 0.00117 0.00139]
实际输出光功率值c =  [8.2500e-05 5.2500e-05 7.3125e-05 8.6875e-05]
转化为dBm的值 =  [-10.83546051 -12.79840697 -11.35934121 -10.61105182]


## 传统光学交叉阵列矩阵与矩阵乘法演示（波分复用）

In [ ]:
# 输入数据矩阵
A = np.array([[1e-3, 0.8e-3, 0.5e-3, 0.2e-3],
              [0.2e-3, 0.4e-3, 0.7e-3, 1e-3],
              [0.5e-3, 0.2e-3, 0.5e-3, 0.8e-3],
              [0.3e-3, 1e-3, 0.8e-3, 0.2e-3]])

# 权重传输率数据矩阵
B = np.array([[1, 1, 1, 1],
              [1, 0.8, 1, 1],
              [1, 1, 0.5, 1],
              [1, 1, 1, 0.3]])

# 权重数据矩阵传输率转化为dB
B_dB = 10 * np.log10(B / 1)
print("权重数据矩阵传输率转化为dB = \n", B_dB)

# 矩阵与矩阵乘法
C = np.matmul(A, B)

# 输出结果
print("矩阵与矩阵乘法输出结果A * B =\n", C)

# 考虑交叉阵列结构平均分配功率
C_out = C / 16
print("实际输出光功率值C =\n", C_out)

# 转化为dBm
C_dBm = 10 * np.log10(C_out / 1e-3)
print("实际输出光功率转化为dBm的值 =\n", C_dBm)

权重数据矩阵传输率转化为dB = 
 [[ 0.          0.          0.          0.        ]
 [ 0.         -0.96910013  0.          0.        ]
 [ 0.          0.         -3.01029996  0.        ]
 [ 0.          0.          0.         -5.22878745]]
矩阵与矩阵乘法输出结果A * B =
 [[0.0025  0.00234 0.00225 0.00236]
 [0.0023  0.00222 0.00195 0.0016 ]
 [0.002   0.00196 0.00175 0.00144]
 [0.0023  0.0021  0.0019  0.00216]]
实际输出光功率值C =
 [[1.56250e-04 1.46250e-04 1.40625e-04 1.47500e-04]
 [1.43750e-04 1.38750e-04 1.21875e-04 1.00000e-04]
 [1.25000e-04 1.22500e-04 1.09375e-04 9.00000e-05]
 [1.43750e-04 1.31250e-04 1.18750e-04 1.35000e-04]]
实际输出光功率转化为dBm的值 =
 [[ -8.06179974  -8.34904125  -8.51937465  -8.3120798 ]
 [ -8.42392147  -8.57767008  -9.14085371 -10.        ]
 [ -9.03089987  -9.11863911  -9.61081934 -10.45757491]
 [ -8.42392147  -8.81900688  -9.25366382  -8.69666232]]


3bit（8级别）差分矩阵元素对应表

8级别的衰减值分别为：-1dB，-1.66dB，-2.44dB，-3.39dB，-4.61dB，-6.30dB，-9.14dB，-20dB

为了确保传输率的增量是线性的，dB值就不能是线性的

| 权重 | 差分正极dB    | 对应传输率 | 差分负极dB     | 对应传输率  |
|------|--------------|-----------|---------------|-------------|
|7     | -1.00dB      |   0.794   |    -20.0dB     |    0.010   |
|6     | -1.00dB      |   0.794   |    -9.14dB     |    0.122   |
|5     | -1.00dB      |   0.794   |    -6.30dB     |    0.234   |
|4     | -1.00dB      |   0.794   |    -4.61dB     |    0.346   |
|3     | -1.00dB      |   0.794   |    -3.39dB     |    0.458   |
|2     | -1.00dB      |   0.794   |    -2.44dB     |    0.570   |
|1     | -1.00dB      |   0.794   |    -1.66dB     |    0.682   |
|0     | -1.00dB      |   0.794   |    -1dB        |    0.794   |
|-1    | -1.66dB      |   0.682   |    -1dB        |    0.794   |
|-2    | -2.44dB      |   0.570   |    -1dB        |    0.794   |
|-3    | -3.39dB      |   0.458   |    -1dB        |    0.794   |
|-4    | -4.61dB      |   0.346   |    -1dB        |    0.794   |
|-5    | -6.30dB      |   0.234   |    -1dB        |    0.794   |
|-6    | -9.14dB      |   0.122   |    -1dB        |    0.794   |
|-7    | -20.0dB      |   0.010   |    -1dB        |    0.794   |

In [10]:
# 正极权重映射dB对应表
mapping_dict_pos = {7: -1, 6: -1, 5: -1, 4: -1, 3:-1, 2:-1, 1:-1, 0:-1, 
                    -1:-1.66, -2:-2.44, -3:-3.39, -4:-4.61, -5:-6.30, -6:-9.14, -7:-20,}
# 负极权重映射dB对应表
mapping_dict_neg = {7: -20, 6: -9.14, 5: -6.30, 4: -4.61, 3:-3.39, 2:-2.44, 1:-1.66, 0:-1,
                    -1:-1, -2:-1, -3:-1, -4:-1, -5:-1, -6:-1, -7:-1}

def weight_to_dB(weight, mapping_dict_pos, mapping_dict_neg):
    """
    将输入的numpy数组按照给定的映射表转换为新的数组。

    参数:
        weight (numpy.array): 输入的numpy数组。
        mapping_dict (dict): 映射表，键是输入数组中的值，值是映射后的值。

    返回:
        W_p_dB: 映射后的正极dB数组。
        W_n_dB: 映射后的负极dB数组。
    """
    # 创建2个与输入数组形状相同的空数组，用于存储映射后的值
    W_p_dB = np.zeros_like(weight)
    W_n_dB = np.zeros_like(weight)

    # 遍历输入数组的每个元素，并根据正极映射表更新输出数组
    for key, value in mapping_dict_pos.items():
        W_p_dB[weight == key] = value

    # 遍历输入数组的每个元素，并根据负极映射表更新输出数组
    for key, value in mapping_dict_neg.items():
        W_n_dB[weight == key] = value

    return W_p_dB, W_n_dB

In [32]:
# 输入向量 单位：mW
a = np.array([1, 0.8, 0.5, 0.2])
print(f"输入向量功率 = {a}\n")

# 原始矩阵数据
B = np.array([[ 2.,  3., -3., -7.],
              [ 2.,  3., -3., -3.],
              [ 1.,  0.,  2., -3.],
              [ 2.,  0.,  1.,  2.]])
print("原始矩阵数据 = \n", B)

# 原始矩阵乘法输出值
c = np.matmul(a, B)
print("原始矩阵乘法输出结果 = ", c)

# 将权重映射到dB
B_p_dB, B_n_dB = weight_to_dB(B, mapping_dict_pos, mapping_dict_neg)

print("差分正极dB矩阵 = \n", B_p_dB)
print("差分负极dB矩阵 = \n", B_n_dB)

# dB转化为传输率
B_p = np.power(10, B_p_dB / 10)
B_n = np.power(10, B_n_dB / 10)
print("差分正极矩阵dB转化为传输率 = \n", B_p)
print("差分负极矩阵dB转化为传输率 = \n", B_n)

# 差分矩阵乘法
c_p = np.matmul(a, B_p)
c_n = np.matmul(a, B_n)

# 差分输出结果
print("差分正极输出结果a * B_p =", c_p)
print("差分负极输出结果a * B_n =", c_n)

# 考虑差分交叉阵列结构平均分配功率
c_out_p = c_p / 32
c_out_n = c_n / 32
print("实际差分正极输出光功率值c = ", c_out_p)
print("实际差分负极输出光功率值c = ", c_out_n)

# 差分转化矩阵乘法功率输出值 单位：mW
c_out_diff = c_out_p - c_out_n
print(f"差分转化矩阵乘法功率输出值 = {c_out_diff}mW")

# 输出功率转化为dBm
c_dBm_p = 10 * np.log10(c_out_p / 1)
c_dBm_n = 10 * np.log10(c_out_n / 1)
print("差分正极转化为dBm的值 = ", c_dBm_p)
print("差分负极转化为dBm的值 = ", c_dBm_n)

# 差分转化矩阵乘法功率输出值 单位：dBm
c_dBm_diff = c_dBm_p - c_dBm_n
print(f"差分转化矩阵乘法功率输出值 = {c_dBm_diff}dBm")

输入向量功率 = [1.  0.8 0.5 0.2]

原始矩阵数据 = 
 [[ 2.  3. -3. -7.]
 [ 2.  3. -3. -3.]
 [ 1.  0.  2. -3.]
 [ 2.  0.  1.  2.]]
原始矩阵乘法输出结果 =  [  4.5   5.4  -4.2 -10.5]
差分正极dB矩阵 = 
 [[ -1.    -1.    -3.39 -20.  ]
 [ -1.    -1.    -3.39  -3.39]
 [ -1.    -1.    -1.    -3.39]
 [ -1.    -1.    -1.    -1.  ]]
差分负极dB矩阵 = 
 [[-2.44 -3.39 -1.   -1.  ]
 [-2.44 -3.39 -1.   -1.  ]
 [-1.66 -1.   -2.44 -1.  ]
 [-2.44 -1.   -1.66 -2.44]]
差分正极矩阵dB转化为传输率 = 
 [[0.79432823 0.79432823 0.45814189 0.01      ]
 [0.79432823 0.79432823 0.45814189 0.45814189]
 [0.79432823 0.79432823 0.79432823 0.45814189]
 [0.79432823 0.79432823 0.79432823 0.79432823]]
差分负极矩阵dB转化为传输率 = 
 [[0.57016427 0.45814189 0.79432823 0.79432823]
 [0.57016427 0.45814189 0.79432823 0.79432823]
 [0.68233869 0.79432823 0.57016427 0.79432823]
 [0.57016427 0.79432823 0.68233869 0.57016427]]
差分正极输出结果a * B_p = [1.98582059 1.98582059 1.38068516 0.7644501 ]
差分负极输出结果a * B_n = [1.48149789 1.38068516 1.8513407  1.94098779]
实际差分正极输出光功率值c =  [0.06205689 0.06205689 